CC=clang++
#CC=g++
CFLAGS=-O -pedantic -Wall

all: bits ints beads

bits: bits.cpp
	$(CC) -o $@ $@.cpp $(CFLAGS)

ints: ints.cpp
	$(CC) -o $@ $@.cpp $(CFLAGS)

beads: beads.cpp
	$(CC) -o $@ $@.cpp $(CFLAGS)
